INSERT INTO FormType
                      (FormTypeID, TypeName)
VALUES     (7, '«” «‰ Â«')



INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (42,'«—œ»Ì·',7,0451)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (43,'«’›Â«‰',7,0311)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (44,'«·»—“',7,026)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (45,'«Ì·«„',7,0841)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (46,'¬–—»«ÌÃ«‰ ‘—ﬁÌ',7,0411)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (47,'¬–—»«ÌÃ«‰ €—»Ì',7,0441)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (48,'»Ê‘Â—',7,0771)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (49,' Â—«‰',7,021)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (50,'Œ—«”«‰',7,0511)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (51,'ŒÊ“” «‰',7,0611)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (52,'“‰Ã«‰',7,0241)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (53,'”„‰«‰',7,0231)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (54,'”Ì” «‰ Ê»·Êç” «‰',7,0541)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (55,'›«—”',7,0711)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (56,'›„',7,0251)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (57,'ﬁ“ÊÌ‰',7,0281)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (58,'ò—œ” «‰',7,0871)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (59,'ò—„«‰',7,0341)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (60,'ò—„«‰‘«Â',7,0831)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (61,'òÂò·ÊÌÂ ',7,0741)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (62,'ê·” «‰ ',7,0171)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (63,'êÌ·«‰',7,0131)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (64,'·—” «‰',7,0662)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (65,'„«“‰œ—«‰',7,0151)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (66,'„—ò“Ì',7,0861)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (67,'Â—„“ê«‰ ',7,0761)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (68,'Â„œ«‰',7,0811)
INSERT INTO FormInfo (FormInfoID, FormInfoName, FormType, FromInfoNo) VALUES (69,'Ì“œ',7,0351)